on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review

jobs:
  check-freeze:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'devel' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: devel
      - uses: actions/github-script@v6
        id: freeze-check
        with:
          result-encoding: string
          script: |
            const fs = require("fs").promises;

            const now = Date.now();
            const freezefile = "freeze.json";
            const freezes = JSON.parse(await fs.readFile(freezefile)).map((freeze) =>
              Object({
                ...freeze,
                start: Date.parse(freeze["start"]),
                end: Date.parse(freeze["end"]),
              })
            );

            const currentFreezes = freezes.filter(
              (freeze) => now > freeze["start"] && now < freeze["end"]
            );
            if (currentFreezes.length > 0) {
              const freeze = currentFreezes[0];
              core.setFailed(
                "We are currently in a freeze from " +
                  `${freeze["start"].toString()} to ${freeze["end"].toString()}`
              );
            }
