on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review

jobs:
  check-freeze:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.base.ref == 'devel'
      && ! contains(github.event.pull_request.body, 'HOTFIX')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: devel
      - uses: actions/github-script@v6
        id: freeze-check
        with:
          result-encoding: string
          script: |
            const fs = require("fs").promises;
            const dtFormat = (dt) => Date(dt).toString();

            const now = Date.now();
            const freezefile = "freeze.json";
            const freezes = JSON.parse(await fs.readFile(freezefile)).map((freeze) =>
              Object({
                ...freeze,
                start: Date.parse(freeze["start"]),
                end: Date.parse(freeze["end"]),
              })
            );

            const currentFreezes = freezes.filter(
              (freeze) => now > freeze["start"] && now < freeze["end"]
            );
            if (currentFreezes.length > 0) {
              const freeze = currentFreezes[0];
              core.setFailed(
                "We are currently in a freeze of devel:\n" +
                  `Start:  ${dtFormat(freeze["start"])}\n` +
                  `End:    ${dtFormat(freeze["end"])}\n` +
                  `Reason: ${dtFormat(freeze["reason"])}\n` +
                  "\n" +
                  "*** If you need to override this check, add the keyword HOTFIX to your PR description!!! ***"
              );
            }
