name: Check Freeze
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review

jobs:
  check-freeze:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.base.ref == 'devel'
      && ! contains(github.event.pull_request.body, 'HOTFIX')
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            freezeIssues = await github.rest.issues.listForRepo({
              ...context.repo,
              state: "open",
              labels: "@freeze",
            });

            const currentFreezes = freezeIssues.data.map((issue) => issue.html_url);
            if (currentFreezes.length > 0) {
              core.setFailed(
                "We are currently in a freeze of devel:\n" +
                  "*** If you need to override this check, add the keyword HOTFIX to your PR description!!! ***\n" +
                  currentFreezes.join("\n")
              );
            }
