name: Create Pre-release

on:
  pull_request:
    branches:
      - release/*
    types: [closed]

jobs:
  create-release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, github.base_ref)
    uses: ./.github/workflows/release_template.yaml
